### PR TITLE
Backend: fix getting parent directory

### PR DESCRIPTION
**Pull request by wloot**
Backend: use recovery umount for /vendor

* See commit messages

### CODE REVIEW

**Comment by osm0sis** [comment]
I can't reproduce the `cd $home/..` issue on Android/recovery mksh or busybox ash:

```:/ # cd /tmp/anykernel
:/tmp/anykernel # home=/tmp/anykernel
:/tmp/anykernel # cd $home/..
:/tmp # cd /
:/ # ash
~ # cd /tmp/anykernel
/tmp/anykernel # home=/tmp/anykernel
/tmp/anykernel # cd $home/..
/tmp #
```

But it's a simple enough change, so I'll add it.

As for the umount, switching back to non-busybox umount will result in a ton of libc spam in recovery.log on system-as-root devices, so you getting 1 line of harmless output is the lesser of 2 annoyances. You really shouldn't even see that since it's all `2>/dev/null`..

**Comment by osm0sis** [comment]
Maybe we need `>/dev/null 2>&1` ? Can you test changing the redirect to that on line 53 and get back to me?

**Comment by wloot** [comment]
> Maybe we need `>/dev/null 2>&1` ? Can you test changing the redirect to that on line 53 and get back to me?

I think not that. It is not by the command itself to output the error, but when recovery was doing "Updating partition details". I dont know about sar, anyway if it is not bad for you to make a hack for orangefox, we should be able to find a better solution.

**Comment by osm0sis** [comment]
I just tested reverting back to recovery umount for vendor only and since it's later in the list there doesn't seem to be any libc spam so that should be good to merge as well. :+1:

**Pull request closed without merging**
