### PR TITLE
Backend: improve prop checking

### PR DESCRIPTION
**Pull request by lzlrd**
Signed-off-by: Laster K. (lazerl0rd) <officiallazerl0rd@gmail.com>

### CODE REVIEW

**Comment by lzlrd** [comment]
Currently, the vendor image's build.prop and ro.vendor.* props are ignored for devicecheck. We should utilise them. GSI ROMs wouldn't include a device's name in most cases and we should be checking vendor.

**Comment by osm0sis** [comment]
Good idea and good catch! What's in a GSI /system/build.prop for those values, out of curiosity?

**Comment by lzlrd** [comment]
@osm0sis I guess they just don't include the device props at all. No reason to confuse applications. I personally don't have any treble devices so :P.

**Comment by osm0sis** [comment]
Check Slack for some changes this will need. :+1:

**Comment by lzlrd** [comment]
@osm0sis hopefully, this checks out.

**Comment by Panchajanya1999** [comment]
btw, @osm0sis 
system_as_root devices cant flash kernels without magisk, shows ramdisk not found.
Using AK3 btw(latest)

**Comment by osm0sis** [comment]
Only A-only or Huawei Treble wouldn't have a ramdisk, but the rest do in some form or another. It's up to developers to know the device they're developing for and for those with no ramdisk, make it avoid unpacking the ramdisk. Instructions are in the README.

**Comment by osm0sis** [comment]
This patch would lose checking /system/build.prop and adds /system/default.prop (which doesn't exist since we're mounted to /system_root and so /system is actually /system), and excludes /vendor/build.prop .. I'm going to revise.

**Comment by lzlrd** [comment]
Thanks for the revise, and sorry for my mini hiatus there.

**Pull request closed without merging**
