### PR TITLE
Sign autodetect

### PR DESCRIPTION
**Pull request by Zackptg5**
Add autodetect of signed boot imgs (along with needed auto slot detection as well).
Reason for this is of course universality. Some devices of course require that the boot img is signed (in the event that it was already signed) but some devices require that it's not and will not boot at all if it's signed.

### CODE REVIEW

**Comment by nathanchance** [comment]
I don't think the binaries should be added, I know for a fact none of my devices need them so I don't want them bloating up my zip. The slot detection changes shouldn't really be a part of this right? That's what #21 is for; if this is totally dependent on them, might be wise to mention that.

Again, Chris will most likely comment on this further so don't take me speaking for him, just providing my input.

**Comment by Zackptg5** [comment]
The slot detection is needed for the sign detection function. I kept out the rest of the slot overlay stuff since it's not part of the boot signing process. 
I just figured since the binaries weren't large, the only thing having it sign automatically would do is slightly increase zip size and increase compatibility. I'm pretty sure some newer devices/roms won't boot without signed boot img (don't quote me on that though)

**Comment by nathanchance** [comment]
Fair enough, Chris can comment about how to break things down depending on what he wants to add.

Honestly, the only device that I know of that has/had that requirement was the Pixel and Pixel XL. The Pixel 2 and Pixel 2 XL uses a different AVB tool for signing and it isn't required (right now).

**Comment by osm0sis** [comment]
There was a much more elegant way to go about this: add the detection of signing below the if statement for whether the jar exists.

That way it's still up to the dev to add the jar to enable the functionality, and devs for devices that don't need it don't have to worry about it.

Ditto what I said about "derp"/underp commits. Please use `git commit --amend` in such cases.

**Comment by osm0sis** [comment]
Again, if you'd just fixed it along the lines of my suggestions, by putting it all under the if -f .jar, etc. this is a great idea. It's also on my to-do for my next stretch of days off (ran out of time today, unfortunately). :+1:

**Pull request closed without merging**
