### PR TITLE
anykernel: Allow to check multiple device names

### PR DESCRIPTION
**Pull request by ghost**
By default ak2 checks only 5 device names. So, check for all the names supplied by user in prop `device.names`

### CODE REVIEW

**Comment by osm0sis** [comment]
FYI, you don't have to close and make a new Pull Request when you make changes, just fix it on your machine, `git add *; git commit --amend` then force push and the Pull Request will update automatically.

**Comment by ghost** [comment]
I don't wanted to force push coz not everyone likes it
So, i did three pulls sorry for it
I'll update this pull as in dash there's no support for arrays,
I was testing code manually in my machine not my phone and I tested now and looks like dash having conflicts with it

**Comment by osm0sis** [comment]
As for your changes, this is an interesting approach, though if there's a way to do it without breaking backwards compatibility that'd be preferable in my mind.. maybe something more extensible like being able to add as many numbered ones as needed?

And no.. Force pushing to your repo for a Pull Request to another is the right way to do it. Force pushing to a repo lots of people follow is annoying, but that's not the case here. So please, no more opening/closing, just fix the one you've got. :+1:

**Comment by ghost** [comment]
img_20181212_225914

It's Working now , tested

**Comment by osm0sis** [comment]
Looks good, but I'd still prefer if any update to this feature were backwards compatible and extensible as I already mentioned. Thanks!

**Comment by ghost** [comment]
> Looks good, but I'd still prefer if any update to this feature were backwards compatible and extensible as I already mentioned. Thanks!

Dash shell isn't a very good shell, it lacks many features as compared to bash.
If bash was supported in ak2 than it can be handled more easily with the help of arrays

**Comment by osm0sis** [comment]
Recovery generally uses ash, not dash, though I'm not sure if that's better or worse, feature-wise! I'll take a look and see what I can figure out.

**Pull request closed without merging**
