### PR TITLE
Change example to go away from Tuna

### PR DESCRIPTION
**Pull request by nift4**
Now only the device name needs to be edited to use this.

### CODE REVIEW

**Comment by osm0sis** [comment]
Nah, I want people to know what they're doing to set up for their target device, and I want examples to show how those commands could be used. This was all intentional.

**Comment by nift4** [comment]
I know this was intentional. But I though maybe it will be merged. Anyway, no problem :)
Two things though:
- Could you maybe enable GitHub issues? [Not about this, but no other way to say]
- Could you provide an patch or something that removes the example as I did, because if I release a new kernel I have to remove the example over and over again.

**Comment by nift4** [comment]
And a big thanks for your useful tool, it's really useful :)

**Comment by osm0sis** [comment]
I appreciate the idea! I've considered it before, but you'll have to commit changes to set it up for your target device anyway, so why wouldn't removing the example be part of that? It's not too extensive.

**Comment by nift4** [comment]
It's true, but sometimes I don't do it via git, only a quick & dirty test; and then a `git clone <repo url> -b ready2go` would be nice :)

**Comment by RebelLion420** [comment]
@nift4 in that case, fork the repo and create your own branch with your changes. You can even add it as a submodule in your source so it's a separate repo still but it ships with your source. Look into it, its what I did for exactly this purpose that you have

_Sent from my OnePlus 7 Pro using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Pull request closed without merging**
