### PR TITLE
anykernel: Don't allow to pass strings with leading and trailing characters '-_.' to file_getprop function

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by osm0sis** [comment]
Why is this necessary?

**Comment by ghost** [comment]
> Why is this necessary?

Just a check to prevent badly formatted strings.
It'll not output the strings which have `.` `_` `-` `:`, etc in start and end.


E.g: 
 `.kernel by random @ xda`,
`.perseus`, 
`perseus.` 
etc


Closing because it's checks and nothing else

**Comment by osm0sis** [comment]
It's a prop, and in the case of the prop section of anykernel.sh it can contain whatever the dev wants for their kernel name string.

As far as I know there's no limitation on what grep, cut, echo (and ui_print) can handle the way I've got it now, so there's no need to limit it.

Thanks for your time.

Edit: = as the delimiter in cut would be the only exception.

**Comment by ghost** [comment]
> It's a prop, and in the case of the prop section of anykernel.sh it can contain whatever the dev wants for their kernel name string.
> 
> As far as I know there's no limitation on what grep, cut, echo (and ui_print) can't handle the way I've got it now, so there's no need to limit it.
> 
> Thanks for your time.
> 
> Edit: = as the delimiter in cut would be the only exception.

I can somehow workaround this limitation
Let's see I think I'll make a pull will like to get your review over it!

**Comment by osm0sis** [comment]
Thanks for the offer, but like I said, it's a minimal and obvious exception, no fix necessary.

Edit: Actually, I just realized a simple fix. So definitely nevermind. :+1:

**Pull request closed without merging**
