### PR TITLE
AK3: use lptools resize for vendor_dlkm

### PR DESCRIPTION
**Pull request by capntrips**
This unmounts, unmaps, resizes, maps, and mounts `vendor_dlkm` rather than using a temporary partition to replace it on disk. It allows increasing the size of the partition when there isn't enough to space to hold an extra copy. It also has the side effect of allowing backup and verification immediately after flashing, whereas the replace method required a reboot first.

Since it seems to be stable, I'm not sure there is any need to maintain both methods.

### CODE REVIEW

**Comment by osm0sis** [comment]
Why doesn't this run into the concerns explained here?: https://github.com/osm0sis/AnyKernel3/pull/69#issuecomment-1113955744

**Comment by capntrips** [comment]
This unmounts and unmaps the partition prior to resizing, I'm guessing when he says system, he means the system partition, which I'm sure can't easily be unmounted.

**Comment by osm0sis** [comment]
Right but this is flash_generic, so we're losing booted flashing support for certain partitions with this change, no?

**Comment by capntrips** [comment]
As with the previous method, it only operates on partitions found in `/dev/block/mapper`, which is assumed to only ever be `vendor_dlkm`. It continues to work booted, but I'm not sure what would happen if it tried to mount the partition in recovery.

**Comment by osm0sis** [comment]
But that definitely includes system, vendor, odm, and others.

Screenshot_20220731-120022

I'd suggest still using resize only as a fallback if replace fails due to lack of space or something.

**Comment by capntrips** [comment]
Ah, I understand what you're saying now. I had taken what is [defined](https://github.com/osm0sis/AnyKernel3/blob/330de65c7711db446b261a35634e473c1badec3f/tools/ak3-core.sh#L496-L505) out of the box in AK3 and a narrow focus on Pixel 6 (that apparently [bled through](https://github.com/capntrips/HashtreePatcher/blob/v2.0.0/main.cpp#L55-L58) into Hashtree Patcher) and ran with it.

I have no idea what the implications would be of taking any of those partitions offline on a running system, so I think it makes sense to keep the `replace` method as the primary method with `resize` (with the implementation reworked to be more generic) as the fallback when not enough space is available for the temporary partition.

I should note that with the `replace` method, if multiple partitions are flashed, I suspect the areas of the disk that are actively mapped by previously replaced partitions risk being overwritten, which might be problematic, especially with verity devices (though I have zero clue how or when the underlying data is verified).

**Comment by engstk** [comment]
> Ah, I understand what you're saying now. I had taken what is [defined](https://github.com/osm0sis/AnyKernel3/blob/330de65c7711db446b261a35634e473c1badec3f/tools/ak3-core.sh#L496-L505) out of the box in AK3 and a narrow focus on Pixel 6 (that apparently [bled through](https://github.com/capntrips/HashtreePatcher/blob/v2.0.0/main.cpp#L55-L58) into Hashtree Patcher) and ran with it.
> 
> I have no idea what the implications would be of taking any of those partitions offline on a running system, so I think it makes sense to keep the `replace` method as the primary method with `resize` (with the implementation reworked to be more generic) as the fallback when not enough space is available for the temporary partition.
> 
> I should note that with the `replace` method, if multiple partitions are flashed, I suspect the areas of the disk that are actively mapped by previously replaced partitions risk being overwritten, which might be problematic, especially with verity devices (though I have zero clue how or when the underlying data is verified).

Yeah, having it more generic and follow ak3 original intend is also better for further expansion.
imo resize is faster, cleaner and robust enough for what we are doing here. But replace first with resize (reworked) falback is probably better.
Although replace isn't without problems. I encountered some situations from what you describe in the last paragraph.
In which the produced cruft doesn't get removed or completed and invalidates further flashing (even without multiple original partitions, but cruft in place from before that multiplies the partitions processed, naming, etc

There's pros and cons.

**Comment by osm0sis** [comment]
When it falls back to resize during a booted flash it should probably print a warning telling people they should reboot immediately after the flash as well. 🙌

**Comment by engstk** [comment]
> When it falls back to resize during a booted flash it should probably print a warning telling people they should reboot immediately after the flash as well. raised_hands

You probably meant replace. Resize doesn't suffer from that, you can flash zips in a row without reboot, it's one of the pros.

**Comment by osm0sis** [comment]
> > When it falls back to resize during a booted flash it should probably print a warning telling people they should reboot immediately after the flash as well. raised_hands
> 
> You probably meant replace. Resize doesn't suffer from that, you can flash zips in a row without reboot, it's one of the pros.

I meant resize, since resize is overwriting the actual active partition, and if that's vendor or odm or system then they'll need to reboot immediately before something inevitably tries to access them and goes boom.

But, to your point, perhaps both should have that warning.

**Comment by engstk** [comment]
> > > When it falls back to resize during a booted flash it should probably print a warning telling people they should reboot immediately after the flash as well. raised_hands
> > 
> > 
> > You probably meant replace. Resize doesn't suffer from that, you can flash zips in a row without reboot, it's one of the pros.
> 
> I meant resize, since resize is overwriting the actual active partition, and if that's vendor or odm or system then they'll need to reboot immediately before something inevitably tries to access them and goes boom.
> 
> But, to your point, perhaps both should have that warning.
vendor_dlkm, (given modules are loaded) would work fine with subsequent flashes using resize without reboots.
You wouldn't be able to flash those ROM partitions without snapshots, cow and all the virtual ab stuff.
For replace there's the mandatory reboot before flashing anything else like was pointed out.
A reboot warning for any of the situation is ok nevertheless.

**Comment by engstk** [comment]
> > > When it falls back to resize during a booted flash it should probably print a warning telling people they should reboot immediately after the flash as well. raised_hands
> > 
> > 
> > You probably meant replace. Resize doesn't suffer from that, you can flash zips in a row without reboot, it's one of the pros.
> 
> I meant resize, since resize is overwriting the actual active partition, and if that's vendor or odm or system then they'll need to reboot immediately before something inevitably tries to access them and goes boom.
> 
> But, to your point, perhaps both should have that warning.

vendor_dlkm (given modules are already loaded) doesn't need a reboot to be able to make subsequent flashes when using resize.
You wouldn't be able to flash those ROM partitions without snapshots, cow and all the virtual ab stuff (or lptools style replace for full OTA partitions).
For replace there's the mandatory reboot before flashing anything else like was pointed out.
A reboot warning for any of the situation is ok nevertheless. But I feel we are focusing a bit in what we could do instead of what we are doing.

**Comment by capntrips** [comment]
I made the commands in Hashtree Patcher generic, and the `avb` and `patch` commands appear to work well enough, though I had little luck with `mount` and `umount`. `modem` was the only other partition I was able to mount and unmount, aside from `vendor_dlkm`.

I didn't see any obvious precedent for retaining a flag through to the end, so I figured I would ask for input on how to make it idiomatic before I dig into it. The best option I can come up with is setting a flag in a temporary file somewhere. Also, it currently doesn't actually check the size of the new partition, just dives into resizing it.

**Review by engstk — APPROVED** [review]
All good for me on OP9P LOS 19.1 and PXL6 A13

**Comment by osm0sis** [comment]
Thanks all!

**Pull request merged**
