### PR TITLE
Support more locations for dtbo img

### PR DESCRIPTION
**Pull request by Zackptg5**
Swiped from magisk

### CODE REVIEW

**Comment by osm0sis** [comment]
Hmm Magisk also has it like the following:

```
find_dtbo_image() {
  DTBOIMAGE=`find /dev/block -iname dtbo$SLOT | head -n 1` 2>/dev/null
  [ ! -z $DTBOIMAGE ] && DTBOIMAGE=`readlink -f $DTBOIMAGE`
}
```

So there might be some stderr to hide and some links to follow, if we're to follow topjohnwu's lead on this one.

**Comment by Zackptg5** [comment]
Good point, did this too quick. Updated pull request with full section

**Comment by nathanchance** [comment]
I'm just curious, what other devices have a dtbo partition, specifically outside of `/dev/block/bootdevice/by-name`?

**Comment by Zackptg5** [comment]
I don't know of any myself but seemed like a good way to future proof it

**Comment by nathanchance** [comment]
Fair enough, was just curious since the current logic works fine on the Pixel 2 XL. I'll pull this in to my tree here in a bit and test (no reason why it shouldn't).

**Review by nathanchance — APPROVED** [review]
Works fine on my Pixel 2 XL.

**Comment by osm0sis** [comment]
Great! Thanks.

**Pull request merged**
