### PR TITLE
AK3: add support for avb patching

### PR DESCRIPTION
**Pull request by capntrips**
This checks for an `avb` option in the `fstab` entry for the current partition. If it finds it, it checks if verity or verification is disabled on the top-level `vbmeta`. If so, it appends a hashtree and FEC data to the partition and updates the hashtree descriptor in the `vbmeta` partition referenced in the `avb` option. I do make the assumption that only logical partitions have the `avb` option.

I tried to make it as generic as possible, so while I limited it to modifying `vendor_dlkm` and `vbmeta`, I had it throw an error if it detects the `avb` option on any other partition flashed with `flash_generic`. It could probably handle it if the `vbmeta` partition had a different name, since it is working with the block device directly, but I figured it would be better to test it, if that is encountered in the wild, before forging ahead.

The output of both the `avb` and `disable-flags` commands is used, but there are error conditions that can cause them to exit prematurely. I tried to handle that in a way that matches the code style of the project, but I didn't see that exact scenario covered, elsewhere. Also, I don't use C++ in my professional life, so I'm also open to suggestions for making the output/exit codes of HashtreePatcher a bit more idiomatic, if you have any suggestions.

I didn't see any existing way to identify if the user has patched their top-level `vbmeta` or if the current partition has an `avb` option, so I added some commands to HashtreePatcher and renamed the binary to httools (HashTree Tools), rather than making a separate binary to test for those conditions.

`fec` is from [here](https://android.googlesource.com/platform/system/extras/+/refs/tags/android-12.1.0_r5/verity/fec/), though I slightly [modified](https://github.com/capntrips/vendor_fec) Android.bp to make it build for devices, and HashtreePatcher is from [here](https://github.com/capntrips/HashtreePatcher/).

**Note:** This has not yet been tested on a device with verity or verification disabled or on a device without an `avb` option on `vendor_dlkm`.

### CODE REVIEW

**Comment by capntrips** [comment]
I tried all four combinations of `--disable-verity` and `--disable-verification`, and the kernel flashed and booted without issue. Interestingly, I was _not_ forced to wipe my data with `--disable-verity`, and that was enough to be able to boot without patching `vendor_dlkm` or `vbmeta`. I tried it twice just to be sure.

I have not tested it on a device without an `avb` option on `vendor_dlkm`. If such a device exists, I do not have one. Maybe I can edit the `fstab` on a Pixel 6.

**Edit:** I tried modifying the `fstab` file in `vendor.img` with `overlayfs` and `build_image` (using a properties file based on [this](https://android.googlesource.com/kernel/gs/+/refs/tags/android-12.1.0_r0.22/vendor_dlkm.props.slider)), but it bootloops and `ramoops` is overwritten in `fastbootd`, so I'm not sure how to debug it.

**Review by Beerpk — APPROVED** [review]

**Comment by osm0sis** [comment]
Still no device to personally test this out, so @engstk + @freak07, how's it look?

**Comment by capntrips** [comment]
It probably couldn't hurt to test it on a device that doesn't support verity, if anyone has one available.

**Comment by osm0sis** [comment]
Are there actually dynamic/logical partition devices that don't support verity?

**Comment by freak07** [comment]
I just tried to flash an updated ak3.zip on my p6pro with verity/verification disabled and the flash failed. 

that´s the log I got from FKM:

https://pastebin.com/t7VPYB3a

**Comment by engstk** [comment]
Can't test this atm, sorry.

**Comment by osm0sis** [comment]
> I just tried to flash an updated ak3.zip on my p6pro with verity/verification disabled and the flash failed.
> 
> that´s the log I got from FKM:
> 
> https://pastebin.com/t7VPYB3a

Looks like the binary isn't fully static, which will need to be fixed, and it didn't anticipate your disabled verity, which will also need to be supported. The segfault is concerning. 🤔

Also you should remove the default ramdisk perms lines in anykernel.sh if you're not including any matching files. And I'll fix that rmdir noise. 🙂

**Comment by capntrips** [comment]
Comparing with `lptools_static`, I didn't include the `static_executable` property in Android.bp. I'll get that added (and `device_supported`, just in case).

As for the segfault, it looks like it is possible for `LoadAndVerifyVbmeta` to [return null](https://android.googlesource.com/platform/system/core/+/refs/tags/android-12.0.0_r12/init/first_stage_mount.cpp#813), so I'll add a check for that, though that won't fix the underlying issue. The error it prints is expected, so that shouldn't be the problem.

**Comment by capntrips** [comment]
After thinking about it a bit, maybe the static issue is the cause of `LoadAndVerifyVbmeta` returning null. I updated the binary with one that should hopefully be fully static. I also added the null check to `disable-flags`.

**Comment by freak07** [comment]
> After thinking about it a bit, maybe the static issue is the cause of `LoadAndVerifyVbmeta` returning null. I updated the binary with one that should hopefully be fully static. I also added the null check to `disable-flags`.

Removed the ramdisk perm lines as suggested by @osm0sis and updated the zip with the updated binary. 
Unfortunately still the same error it seems, but still some progress. :)

https://pastebin.com/HcZWiguL

I´m still on Magisk 24309. Could that make a difference?

**Comment by capntrips** [comment]
If nothing else, at least the linker errors and segfault are gone. As for 24309, I wouldn't think that is the issue, as I'm fairly certain at least some of my testing was done on 24307. I'll try it with 24309 tomorrow, just to eliminate it as a factor. Assuming that doesn't trigger something, I'll put some print statements in a test build to try to narrow down the source of the issue. Maybe I'll stumble over something while tracing the function calls.

I assume you're using the stock `vbmeta`, aside from the disable flags? Did you disable both verity and verification? I don't suppose there's anything interesting in your `logcat` when you run the command?

**Review by engstk — APPROVED** [review]

**Comment by engstk** [comment]
Ok with Verity and Verify on, patches and boots with Magisk 24315.
No errors with FKM and @capntrips Kernel Flasher

https://pastebin.com/Vy8wJLNE
https://pastebin.com/JGXGwQud

**Comment by capntrips** [comment]
> https://pastebin.com/Vy8wJLNE

I see you still have the following line in your output:

> WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"

Were you using the binary that I committed 8 hours ago?

**Comment by engstk** [comment]
> > https://pastebin.com/Vy8wJLNE
> 
> I see you still have the following line in your output:
> 
> > WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
> 
> Were you using the binary that I committed 8 hours ago?

Yep, latest commit.

**Comment by freak07** [comment]
> If nothing else, at least the linker errors and segfault are gone. As for 24309, I wouldn't think that is the issue, as I'm fairly certain at least some of my testing was done on 24307. I'll try it with 24309 tomorrow, just to eliminate it as a factor. Assuming that doesn't trigger something, I'll put some print statements in a test build to try to narrow down the source of the issue. Maybe I'll stumble over something while tracing the function calls.
> 
> I assume you're using the stock `vbmeta`, aside from the disable flags? Did you disable both verity and verification? I don't suppose there's anything interesting in your `logcat` when you run the command?

I'll try to give it another go with latest canary later today and grab a logcat as well. It's a holiday here today, not at home currently. 

Correct verity and verification were disabled when I flashed may firmware. I'm also on stock may vbmeta from raven factory image.

**Comment by capntrips** [comment]
> WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"

I'm not getting that at all when I run it directly. I'm seeing mention of `proot` with a Google search, and [this](https://forum.xda-developers.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple-devices-platforms.2239421/post-79928640) mentions `chroot` with FKM, for whatever that's worth, though I have no idea why it would affect [this](https://pastebin.com/Vy8wJLNE) run, but not [this](https://pastebin.com/HcZWiguL) one.

**Comment by freak07** [comment]
> > WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
> 
> I'm not getting that at all when I run it directly. I'm seeing mention of `proot` with a Google search, and [this](https://forum.xda-developers.com/t/tools-zips-scripts-osm0sis-odds-and-ends-multiple-devices-platforms.2239421/post-79928640) mentions `chroot` with FKM, for whatever that's worth, though I have no idea why it would affect [this](https://pastebin.com/Vy8wJLNE) run, but not [this](https://pastebin.com/HcZWiguL) one.

alright here´s a logcat flashing via exkm on latest magisk 24316 with verity/verification flags disabled on june firmware

https://pastebin.com/SUgGbueT

that´s the FKM log of the same flash:

https://pastebin.com/quQz2PZ1


Interestingly the linker error is present in the logcat. I also see it in logcat when flashing via exkm, but not in the FKM log that´s generated by the app.

**Comment by capntrips** [comment]
> [libfs_avb]vbmeta: allow verification error is not allowed

That message comes from [here](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:system/core/fs_mgr/libfs_avb/avb_util.cpp;l=578). `allow_verification_error` is set with `IsAvbPermissive()` [here](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:system/core/fs_mgr/libfs_avb/fs_avb.cpp;l=380). I'm not seeing [this message](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:system/core/fs_mgr/libfs_avb/fs_avb.cpp;l=274) in your `logcat`, so the only option I'm seeing for it to be false is for `IsDeviceUnlocked()` to return false [here](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:system/core/fs_mgr/libfs_avb/fs_avb.cpp;l=271). So somehow your device is unable to find `verified_boot_state` [here](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:system/core/fs_mgr/libfs_avb/util.cpp;l=112) or it isn't orange?

I suppose a simple solution would be to rewrite the `LoadAndVerifyVbmeta()` call and manually provide the options from [here](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:system/core/fs_mgr/libfs_avb/fs_avb.cpp;l=377), with `allow_verification_error` set to true, bypassing `IsAvbPermissive()` altogether.

**Comment by capntrips** [comment]
@freak07 I went for the simple solution, if you wouldn't mind giving it another try. I think it is safe to assume that anyone running this has their bootloader unlocked.

@osm0sis According to [this](https://stackoverflow.com/a/55664341), the `httools_static` binary really is static, so I don't think that warning is a concern:

[readelf-program-headers-static](https://github.com/osm0sis/AnyKernel3/files/8847737/readelf-program-headers-static.txt)
[readelf-program-headers-shared](https://github.com/osm0sis/AnyKernel3/files/8847739/readelf-program-headers-shared.txt)

**Comment by freak07** [comment]
> @freak07 I went for the simple solution, if you wouldn't mind giving it another try. I think it is safe to assume that anyone running this has their bootloader unlocked.
> 
> @osm0sis According to [this](https://stackoverflow.com/a/55664341), the `httools_static` binary really is static, so I don't think that warning is a concern:
> 
> [readelf-program-headers-static](https://github.com/osm0sis/AnyKernel3/files/8847737/readelf-program-headers-static.txt) [readelf-program-headers-shared](https://github.com/osm0sis/AnyKernel3/files/8847739/readelf-program-headers-shared.txt)

flashed fine on june firmware, 24316, verity/verification disabled

logcat:
https://pastebin.com/mwtJf0UU

fkm log:
https://pastebin.com/y6rBMUS7

**Comment by freak07** [comment]
I received confirmation from a tester that the zip also flashed fine on 24316 canary and having verity/verification flags enabled.

**Comment by osm0sis** [comment]
Sounds positive! Hmm so does that all mean we're good to go?

**Comment by capntrips** [comment]
An XDA member referenced a tool called [`avbctl`](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:external/avb/tools/avbctl/avbctl.cc) today, if it makes more sense to bundle that, rather than using the `disable-flags` command from Hashtree Patcher; otherwise, I think it's good to go. This PR was included in the Kirisakura 3.0.0 [release](https://forum.xda-developers.com/t/kernel-07-06-2022-android-12-1-0-kirisakura-3-0-0-for-pixel-6-pro-aka-raviole.4358435/post-86992705), so I'm guessing we'll find out very quickly if there are any lingering issues.

**Comment by engstk** [comment]
> An XDA member referenced a tool called [`avbctl`](https://cs.android.com/android/platform/superproject/+/android-12.1.0_r5:external/avb/tools/avbctl/avbctl.cc) today, if it makes more sense to bundle that, rather than using the `disable-flags` command from Hashtree Patcher; otherwise, I think it's good to go. This PR was included in the Kirisakura 3.0.0 [release](https://forum.xda-developers.com/t/kernel-07-06-2022-android-12-1-0-kirisakura-3-0-0-for-pixel-6-pro-aka-raviole.4358435/post-86992705), so I'm guessing we'll find out very quickly if there are any lingering issues.

If this is the only block, probably should be merged and that changes can come to a second PR and round of testing.
I shipped with this today also, awesome work @capntrips

**Review by engstk — APPROVED** [review]

**Comment by osm0sis** [comment]
Sounds good to me! Bombs away!

**Comment by osm0sis** [comment]
@capntrips I just gave this one final look over and I'm not seeing the fec binary in use anywhere? Maybe just one more commit to remove the unused binary and take it out of the license?

**Comment by capntrips** [comment]
`fec` is used by Hashtree Patcher to generate the FEC data that is appended during the `patch` operation. That is also why it changes to the tools dir to run that operation, as it looks in cwd for that file. It isn't strictly required, but `avbtool` does use it by default. The idea is it adds some error correction, so it doesn't mark everything as corrupt due to a few bits flipping somewhere.

**Comment by osm0sis** [comment]
Ah perfect, thanks for explaining. Good to go then!

**Pull request merged**
